config/routes.rb
Buckets::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations"}
  resources :todos

  root to: "home#index"

  resources :users
  resources :categories
  resources :todos

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :todos, :dependent => :destroy

  validates_presence_of :name

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  scope :completed, lambda { where(:complete => "completed") }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :trackable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :token_authenticatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  respond_to :json

  def index
    # render :json => Category.all.includes(:todos)
    @categories = Category.all.includes(:todos)
    logger.info @categories.to_json
    respond_with @categories
  end

  def show
    respond_with Category.find(params[:id])
  end

  def create
    respond_with Category.create(category_params)
  end

  def update
    respond_with Category.update_attributes(category_params)
  end

  def destroy
    respond_with Category.destroy(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name, :position)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  respond_to :json
  
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :json

  def create
    resource = User.find_for_database_authentication(:email => params[:user][:email])
    return invalid_email unless resource
 
    if resource.valid_password?(params[:user][:password])
      sign_in(:user, resource)
      resource.ensure_authentication_token!
      render :json=> {:success=>true, :auth_token=>resource.authentication_token, :email=>resource.email}
      return
    end
    invalid_login_attempt  
  end
  
  protected
   
  def invalid_email
    render :json=> {:success=>false, :message=>"Invalid email."}, :status=>200
  end

  def invalid_login_attempt
    render :json=> {:success=>false, :message=>"Invalid login or password."}, :status=>200
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :update, :edit, :destroy]
  respond_to :json

  def index
    @todos = Todo.all
  end

  def show
    respond_with @todo
  end

  def new
    @todo = Todo.new
  end

  def edit
    respond_with @todo
  end

  def create
    respond_with Todo.create(todo_params)
  end

  def update
    respond_with @todo.update_attributes(todo_params)
  end

  def destroy
    respond_with @todo.destroy
  end

  private
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:title, :category_id, :body, :complete, :up_votes).reject { |k,v| v.nil? }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json

  def show
    respond_with User.find(params[:id])
  end

  def update
    respond_with User.find(params[:id]).update_attributes(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title List Bucket
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  
  %body
    %script
      window.user_id = #{current_user.id if current_user}
    .bg S
    .bg.bg-right F

    - unless current_user
      = link_to_function "sign in", "$('#sign-in-modal').fadeIn(); $('#sign-up-modal').fadeOut()"
      |
      = link_to_function "sign up", "$('#sign-up-modal').fadeIn(); $('#sign-in-modal').fadeOut();"
    - else
      = link_to "sign out", destroy_user_session_path, method: :delete
      
    = yield

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :up_votes %><br>
    <%= f.number_field :up_votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Body</th>
      <th>Up votes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.category %></td>
        <td><%= todo.body %></td>
        <td><%= todo.up_votes %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @todo.category %>
</p>

<p>
  <strong>Body:</strong>
  <%= @todo.body %>
</p>

<p>
  <strong>Up votes:</strong>
  <%= @todo.up_votes %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>